[package]
name = "hyperium"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
html_parser = "0.7.0"
reqwest = { version = "0.12.5", features = ["brotli", "cookies"] }
tokio = { version = "1.38.0", features = ["full"] }
